import React from 'react'
import { Image } from "@chakra-ui/react";
import Head from 'next/head';
import Department from '../../components/Staff/Department'


const description = "Go Global School has been founded by a group of educational specialists, who collectively hold over 10 years of experience in the field. The curriculum has been developed in accordance with the academic programme set by the Ministry of Education, Youth, and Sport of The Kingdom of Cambodia and the British National Curriculum.";
const currentURL = "https://www.go-globalschool.com/";
const previewImage = '../link_image.jpg'
const siteName = "Go Global School"
export default function StaffPage(props) {

    return (
        <div>
            <Head>
                <title>{props.name} | Go Global School</title>
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />

                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content={description}></meta>

                <meta property="og:title" content={props.name} key="ogtitle" />
                <meta property="og:url" content={currentURL} key="ogurl" />
                <meta property="og:image" content={previewImage} key="ogimage" />
                <meta property="og:site_name" content={siteName} key="ogsitename" />
                <meta property="og:description" content={description} key="ogdesc" />
            </Head>
            <Department depTitle={props.name} allMember={props.member}/>
        </div>
    )
}
