import React from 'react'
import { Center, Box, Image} from "@chakra-ui/react";
import DztImageGalleryComponent from "reactjs-image-gallery";
// https://www.npmjs.com/package/reactjs-image-gallery
import Head from 'next/head'
import {motion} from "framer-motion"
const MotionBox = motion(Box)

export default function ActivityDetail({ des, name, featurImages }) {
    let container = { sm: "100%", md: "100%", lg: "98%", xl: "80%", "2xl": "80%" };
    let widthBody = { sm: "100%", md: "90%", lg: "90%", xl: "80%", "2xl": "80%" };
    let title = {base: "28px",sm: "40px",md: "45px",lg: "50px",xl: "50px",'2xl': "50px"};
    let body_Text = { base: "16px", sm: "20px", md: "20px", lg: "20px", xl: "20px", '2xl': "20px" };
    const top = {
        base: "70px", //0px
        sm: "90px",  //320px
        md: "90px",  //768px
        lg: "30px",  //960px
        xl: "30px",  //1200px
        '2xl': "30px"  //1536px
    }
    const description = "Go Global School has been founded by a group of educational specialists, who collectively hold over 10 years of experience in the field. The curriculum has been developed in accordance with the academic programme set by the Ministry of Education, Youth, and Sport of The Kingdom of Cambodia and the British National Curriculum.";
    const currentURL = "https://www.go-globalschool.com/";
    const previewImage = '../link_image.jpg'
    const siteName = "Go Global School"
    return (
        <Center >
            <Head>
                <title>{name} | Go Slobal School</title>
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="description" content={des}></meta>
                <meta property="og:title" content={name} key="ogtitle" />
                <meta property="og:url" content={currentURL} key="ogurl" />
                <meta property="og:image" content={previewImage} key="ogimage" />
                <meta property="og:site_name" content={siteName} key="ogsitename" />
                <meta property="og:description" content={des} key="ogdesc" />
            </Head>
            <Box
                width={container}
                p="20px"
                mt={top}
            >      
                    <MotionBox 
                        initial={{ x: -100, opacity: 0 }}
                        animate={{ x: 0, opacity: 1 }}
                        transition={{ delay: 1, duration: 1.5 }}
                    >
                        <Center>
                            <Image src="../vission.png" />
                        </Center>
                    </MotionBox>
                    <Center>
                    <MotionBox
                        fontSize={title}
                        fontFamily="Sushi Delivery Regular"
                        letterSpacing="3px"
                        color="brand.100"
                        initial={{ x: -100, opacity: 0 }}
                        animate={{ x: 0, opacity: 1 }}
                        transition={{ delay: 0.2, duration: 1.2 }}
                    >
                        {name}
                    </MotionBox>
                    </Center>
                <Center>
                    <Box 
                        w={widthBody} 
                        align="justify" 
                        mt='20px' 
                        color="brand.100" 
                        fontSize={body_Text}
                    >
                        {des}
                    </Box>
                </Center>
                <Center>
                    <DztImageGalleryComponent images={featurImages} />
                </Center>
            </Box>
        </Center>
    )
}
